version: "3"

services:
  main-app:
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - NEXT_PUBLIC_CLOUDINARY_FOLDER=${NEXT_PUBLIC_CLOUDINARY_FOLDER}
      - REVALIDATION_KEY=${REVALIDATION_KEY}
    volumes:
      - app-data:/app/data
      - ./logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/certbot/conf:/etc/letsencrypt
      - ~/certbot/www:/var/www/certbot
    depends_on:
      - main-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local
