FROM node:20-alpine AS builder 

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY apps/main/package.json ./apps/main/
COPY packages/eslint-config/package.json ./packages/eslint-config/
COPY packages/prettier-config/package.json ./packages/prettier-config/
COPY packages/tailwind-config/package.json ./packages/tailwind-config/
COPY packages/tsconfig/package.json ./packages/tsconfig/
COPY packages/ui/package.json ./packages/ui/

RUN npm install -g pnpm 
RUN pnpm install --frozen-lockfile

COPY apps/main ./apps/main
COPY packages ./packages
COPY turbo.json ./turbo.json

RUN pnpm --filter main build

FROM node:20-alpine AS runner
WORKDIR /app 

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN npm install -g pnpm

COPY --from=builder /app/apps/main/next.config.js ./
COPY --from=builder /app/apps/main/public ./public
COPY --from=builder /app/apps/main/.next ./.next
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install --prod --frozen-lockfile
RUN chown -R nextjs:nodejs /app/.next

USER nextjs

EXPOSE 3000
ENV HOSTNAME=0.0.0.0

CMD ["pnpm", "start"]


