FROM node:20-alpine AS builder 

WORKDIR /app

ARG NOTION_API_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG CLOUDINARY_URL
ARG NEXT_PUBLIC_CLOUDINARY_FOLDER
ENV NOTION_API_KEY=${NOTION_API_KEY}
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENV CLOUDINARY_URL=${CLOUDINARY_URL}
ENV NEXT_PUBLIC_CLOUDINARY_FOLDER=${NEXT_PUBLIC_CLOUDINARY_FOLDER}

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY packages/tsconfig/package.json ./packages/tsconfig/
COPY packages/eslint-config/package.json ./packages/eslint-config/
COPY packages/prettier-config/package.json ./packages/prettier-config/
COPY packages/tailwind-config/package.json ./packages/tailwind-config/
COPY packages/ui/package.json ./packages/ui/
COPY apps/main/package.json ./apps/main/

RUN npm install -g pnpm 
RUN pnpm install --frozen-lockfile

COPY apps/main ./apps/main
COPY packages ./packages
COPY turbo.json ./turbo.json

RUN pnpm turbo run build

FROM node:20-alpine AS runner
WORKDIR /app 

ARG NOTION_API_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG CLOUDINARY_URL
ARG NEXT_PUBLIC_CLOUDINARY_FOLDER
ENV NOTION_API_KEY=${NOTION_API_KEY}
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENV CLOUDINARY_URL=${CLOUDINARY_URL}
ENV NEXT_PUBLIC_CLOUDINARY_FOLDER=${NEXT_PUBLIC_CLOUDINARY_FOLDER}
ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN npm install -g pnpm

COPY --from=builder /app/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY --from=builder /app/apps/main/package.json ./apps/main/package.json
COPY --from=builder /app/apps/main/next.config.js ./apps/main/next.config.js
COPY --from=builder /app/apps/main/public ./apps/main/public
COPY --from=builder /app/apps/main/.next ./apps/main/.next
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install --prod --frozen-lockfile
RUN chown -R nextjs:nodejs /app/apps/main/.next

USER nextjs

EXPOSE 3000
ENV HOSTNAME=0.0.0.0

CMD ["pnpm", "run", "--dir", "apps/main", "start"]


