name: Build and Deploy Next.js App

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: na-hyunwoo/wooslog-v2/main
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/main/dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 최신 이미지 가져오기
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

            # 필요한 디렉토리 생성
            mkdir -p ~/nginx/conf.d ~/certbot/conf ~/certbot/www ~/logs

            # nginx 기본 설정 파일 생성
            cat > ~/nginx/nginx.conf << 'EOL'
            user nginx;
            worker_processes auto;

            error_log /var/log/nginx/error.log warn;
            pid /var/run/nginx.pid;

            events {
                worker_connections 1024;
            }

            http {
                include /etc/nginx/mime.types;
                default_type application/octet-stream;
                
                log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';
                
                access_log /var/log/nginx/access.log main;
                
                sendfile on;
                keepalive_timeout 65;
                
                include /etc/nginx/conf.d/*.conf;
            }
            EOL

            cat > ~/nginx/conf.d/app.conf << 'EOL'
            server {
                listen 80;
                server_name devna.xyz www.devna.xyz;
                
                location /.well-known/acme-challenge/ {
                    root /var/www/certbot;
                }
                
                location / {
                    return 301 https://$host$request_uri;
                }
            }

            server {
                listen 443 ssl;
                server_name devna.xyz www.devna.xyz;
                
                ssl_certificate /etc/letsencrypt/live/devna.xyz/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/devna.xyz/privkey.pem;
                
                # 강화된 SSL 설정
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_prefer_server_ciphers off;
                ssl_session_cache shared:SSL:10m;
                ssl_session_timeout 1d;
                
                # 보안 헤더 추가
                add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
                add_header X-Content-Type-Options nosniff;
                add_header X-Frame-Options SAMEORIGIN;
                add_header X-XSS-Protection "1; mode=block";
                
                location / {
                    proxy_pass http://main-app:3000;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
            EOL

            # docker-compose 파일 생성
            cat > ~/docker-compose.yml << 'EOL'
            version: '3'

            services:
              main-app:
                image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                restart: always
                ports:
                  - "3000:3000"
                environment:
                  - NODE_ENV=production
                  - NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}
                  - NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
                  - NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
                volumes:
                  - app-data:/app/data
                  - ./logs:/app/logs
                networks:
                  - app-network
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:3000"]
                  interval: 30s
                  timeout: 10s
                  retries: 3
                  start_period: 40s
                deploy:
                  resources:
                    limits:
                      cpus: '0.5'
                      memory: 512M

              nginx: 
                image: nginx:alpine
                container_name: nginx-proxy
                restart: always
                ports:
                  - "80:80"
                  - "443:443"
                volumes:
                  - ./nginx/conf.d:/etc/nginx/conf.d
                  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                  - ./certbot/conf:/etc/letsencrypt
                  - ./certbot/www:/var/www/certbot
                depends_on:
                  - main-app
                networks:
                  - app-network

            networks:
              app-network:
                driver: bridge

            volumes:
              app-data:
                driver: local
            EOL

            # 인증서 자동 갱신 cron 작업 설정
            (crontab -l 2>/dev/null | grep -v "certbot renew" || true; echo "0 3 * * * docker run --rm --name certbot-renew -v ~/certbot/conf:/etc/letsencrypt -v ~/certbot/www:/var/www/certbot certbot/certbot renew --webroot -w /var/www/certbot && docker exec nginx-proxy nginx -s reload") | crontab -

            # 배포 실행
            cd ~
            docker-compose down
            docker-compose up -d

            # 미사용 이미지 정리
            docker image prune -af
